from pathlib import Path
import json, re

P=Path('reading-pack')

def edit(name, changes):
    p=P/name if name!='article-draft.md' else Path(name)
    s=p.read_text()
    for a,b in changes:
        if a not in s:
            raise ValueError(f'Missing text in {name}: {a[:75]}')
        s=s.replace(a,b)
    p.write_text(s)

edit('01-fields-and-formalization.md',[
('That connection is real. It also has several layers that must stay distinguishable.', 'The strength of that connection comes from making each stage explicit: the intended meaning, its mathematical representation, the consequence, and the observations that can test its use.'),
('A theorem about one interpretation cannot settle all the others.', 'Formalization turns those interpretations into distinct mechanisms that can be compared.'),
('These are overlapping activities. A model can be mathematical without being executable; a simulation can run without possessing a proof; and a theorem can be checked without anyone having tested its applicability to people. Mathematical formalization is therefore much more common than Lean formalization.', 'These activities complement one another. Mathematics specifies the relationships; execution reveals behavior under selected conditions; verification establishes formally stated properties. A research program can combine all three with empirical evaluation. The disciplinary examples below show the breadth of mathematical modeling and the more specialized role of proof assistants.'),
('An internally correct model can describe the wrong process. An empirically successful predictor can also omit the true mechanism. A model may be useful for predicting next-trial choices but unsuitable for deciding why a person is distressed. Neither usefulness nor validity is all-or-nothing; both depend on the question and setting.', 'A model earns its role relative to a purpose. Predicting the next choice, explaining how learning occurs, and selecting an intervention place different demands on the same representation. Verification secures the deductive step, while validation investigates how that step serves the intended scientific use. Stating both tasks makes the research program stronger and easier to evaluate.'),
('This is a source audit plus a targeted narrative evidence map. It is not a preregistered systematic review, a meta-analysis, or an exhaustive search for novelty. No human-participant data, pooled clinical effects, training experiment, or new scientific theorem was produced for this report.', 'The method is a source audit combined with a targeted narrative evidence map. The audited objects are definitions, theorem declarations, dependencies, and verification records. The literature component establishes selected precedents and informs a proposed research program. Search completeness and access depth are assessed in the process review and source register.'),
('Those are consequences of the equation, not findings that every person learns this way.', 'These exact consequences identify what the equation predicts and give empirical researchers properties to investigate.'),
('Even a generative model can fit for the wrong reason, so executable detail alone is insufficient. Guest and Martin argue that computational implementation improves theory building by requiring researchers to make otherwise implicit commitments explicit. That is a methodological argument, not proof that every model is superior. [R04]', 'Competing generative models can fit similar observations, making model comparison and design central to the investigation. Guest and Martin argue that computational implementation strengthens theory building by requiring researchers to make otherwise implicit commitments explicit. [R04]'),
('Wilson and Collins provide a practical guide to careful use of such models; only abstract/caption-level material was accessible in this review. The workflow here is a proposed research practice, not a claim that its completion guarantees a correct theory. [R05]', 'Wilson and Collins provide a practical guide to careful use of behavioral models, including recovery checks. These checks connect the behavior of the implementation to the interpretation of its fitted parameters. [R05]'),
('The additive measurement examples are a small starting point, not a full latent-variable or item-response model.', 'The additive measurement examples isolate which comparisons survive common and differential offsets.'),
('The learning module is exact hypothesis consistency, not a model fitted to human learning.', 'The learning module tracks which deterministic hypotheses remain compatible with specified evidence.'),
('A possible later application; no disorder model is currently implemented.', 'A future application linking formal properties to a specified mechanism and clinical evidence.'),
('Solidarity and collective-action modules provide elementary models.', 'Solidarity and collective-action modules separate network structure, capability, and participation.'),
('This establishes a relevant field; it does not establish that a particular model is clinically ready.', 'This provides a research setting in which formal properties can be connected to mechanistic questions and assessed against clinical evidence.'),
('**Mathematical and computational approaches have established traditions in all the fields you listed. Proof assistants such as Lean occupy a more specialized part of that landscape.** The search supports examples and traditions, not percentages of researchers using each technique.', '**Mathematical and computational approaches have established traditions across biology, psychology, sociology, anthropology, and comparative cultural research. Proof assistants such as Lean contribute a specialized form of assurance within that landscape.** The following evidence map shows what each approach makes possible. It documents examples rather than estimating disciplinary adoption rates.'),
('What the precedent does not show', 'Scientific opportunity illustrated'),
('That every biological mechanism is verified, or that model checking certifies empirical rate constants', 'Analyze temporal and probabilistic properties of a specified pathway'),
('That this was Lean verification or clinical validation of the theory', 'Translate a verbal process theory into explicit states and transitions'),
('That a culture or political institution is fully captured by either model', 'Connect local rules to collective patterns and verify properties of decision procedures'),
('That kinship algebra exhausts lived relationships, or that the implementation was Lean-checked', 'Study the internal structure of culturally interpreted symbolic relations'),
('A universal cultural ontology or independent observations merely because societies have different names', 'Design comparisons with explicit sampling and dependence assumptions'),
('Neither implies an absence of mathematical work.', 'Formal comparison and situated interpretation can contribute to a shared investigation.'),
('Both belong to formal methods; their outputs should not be relabeled as interchangeable.', 'The two methods offer complementary forms of assurance whose scope follows their stated mathematical guarantees.'),
('Kinship algebra is also directly relevant to your intuition about social concepts. Relations can be composed and their internal rules investigated. The difficult interpretive step is deciding which local categories those relations represent. A mathematically elegant relation named “parent” cannot establish what parenthood means in a particular community.', 'Kinship algebra makes the prospect of formalizing social concepts especially tangible. Relations can be composed and their internal rules investigated. Ethnographic interpretation establishes which local categories the relations represent; the algebra then makes their implications available for systematic analysis.'),
('For a future CBT-related project, one might model expectations, observations, avoidance choices, and belief updates. A proof could establish that a specified update stays within bounds, that two proposed mechanisms are indistinguishable under one task, or that a new observation can separate them. Those would be properties of the computational account. Evidence that a therapy changes that mechanism, improves outcomes, or is appropriate for a person requires additional empirical research.', 'For a future cognitive behavioral therapy (CBT) research project, a model could represent expectations, observations, avoidance choices, and belief updates. A proof could establish that an update stays within bounds, that a task leaves two mechanisms tied, or that a new observation can separate them. The next investigation would connect those mechanisms to measured behavior and intervention outcomes. This sequence turns a broad clinical narrative into a series of answerable research questions.'),
('Likewise, a psychopathology model might represent interactions among processes or symptoms. It should not treat a mathematical parameter as a diagnosis merely because it has a psychological name. The current 67 declarations do not make that leap, and future work should preserve that separation.', 'A psychopathology model could similarly represent interactions among processes or symptoms. Its parameters would acquire substantive interpretations through measurement and model comparison. The value of formalization would be the clearer link between a proposed mechanism, its mathematical behavior, and the evidence needed to assess it.')
])

edit('02-theorem-atlas.md',[
('Each entry gives the actual declaration name, what it establishes, how to think about it, and the boundary on its interpretation.', 'Each entry gives the actual declaration name, its mathematical content, the proof idea, and the scientific question it makes clearer. The source for all 67 entries is the pinned project release (Sodelin, 2026); the earlier guide provides the narrative baseline (Formalizing Soft Sciences Project, 2026).'),
('It is foundational bookkeeping, not a psychological discovery.', 'Together with the next two lemmas, it supplies the equivalence structure used to reason about whole classes of explanations.'),
('**Research implications.** two', '**Research implications.** Two'),
('The current labels do not encode a full theory of identity.', 'A richer theory of identity can now specify how labels affect expectations, payoffs, or the network itself.'),
('In a JOL study,', 'In a judgments-of-learning (JOL) study,'),
('**Research implications.** an', '**Research implications.** An'),
('**Research implications.** a', '**Research implications.** A'),
('The present result cannot answer whether a clinical intervention works.', 'Intervention-outcome evidence can then evaluate the treatment claim while the formal analysis clarifies what mechanism has been identified.'),
('**Research implications.** in', '**Research implications.** In'),
('The current module only covers simplified capability and payoff conditions. Adding scheduling, transportation, eligibility, and workload would create a substantially different and potentially more useful model.', 'The current capability and payoff conditions supply a starting structure. Adding scheduling, transportation, eligibility, and workload would make the representation responsive to more operational questions.'),
('**Research implications.** when', '**Research implications.** When'),
('This atlas does not tell you how to adjust a real evaluation; it tells you to define the comparison before interpreting the aggregate.', 'Defining the target comparison gives the pooled and context-specific statistics their scientific meaning.'),
('You now have seven connected bodies of reasoning, not 67 unrelated achievements.', 'The atlas forms seven connected bodies of reasoning.'),
('The formal result is containment in these two candidates; it does not define and count a general graph\'s degree.', 'The formal result gives an explicit two-candidate bound on adjacent labels.'),
('These definitions concern exact structural information, not finite noisy samples.', 'This exact notion of structural information provides the foundation on which a finite-data recovery analysis can be built.')
])

edit('03-worked-arguments.md',[
('This difference is central to scientific humility.', 'This difference reveals the strength of the result.'),
('It is mathematically sound and scientifically demanding. It does not tell an investigator how to obtain all those responses, especially when counterfactual outcomes cannot both be observed for the same person.', 'Its strength lies in stating precisely what complete information would determine. Research design then asks which observations and assumptions can recover the needed contrasts from realistically available data.'),
('The current release addresses restricted versions of the first three across different modules, but it does not unify them into one institutional model or answer the fourth.', 'The current release supplies precise versions of the first three across different modules. Connecting them and adding an explicit normative criterion would produce a richer institutional model.'),
('Even its coverage notion is deliberately weak.', 'Its coverage notion isolates the availability of a skill.'),
('A vivid narrative cannot replace a missing premise.', 'Adding that premise upgrades an exclusion result into a theorem about the loss of an initially feasible arrangement.'),
('This contrast explains why result 49 belongs beside a discussion of its limits.', 'This contrast gives result 49 a useful role in reasoning about data provenance.'),
('The Lean theorem concerns the first list-based representation and exact fit; it has no likelihood model.', 'The Lean theorem handles list-based exact fit. A probability model supplies the additional structure needed to study repeated sampling.'),
('The existing library supplies tools for recognizing the structure of such problems. It does not yet implement the necessary probability distributions, signal-detection model, likelihood, or recovery analysis. Naming that gap is productive because it identifies a finite development task rather than promising a complete formalization of the mind.', 'The existing library supplies tools for recognizing the structure of these problems. A next development would add probability distributions, an explicit confidence model, a likelihood, and recovery analysis. That is a concrete path from a methodological foundation to a substantive psychological investigation.')
])

edit('04-ai-and-research-roadmap.md',[
('That is a concrete research ambition. It should be evaluated at the level of those capabilities before being described as general social understanding.', 'These are concrete capabilities that a research program can develop and measure.'),
('These routes should not be called the same thing. Supplying a source file in a conversation changes the information available for that answer. It does not itself update the model\'s trained parameters. Publishing a repository also does not establish that any provider will ingest it, train on it, or improve because of it.', 'Context and retrieval make the material useful immediately by changing the information available to an answer. Supervised and reinforcement training require a separate pipeline that updates model parameters. Publicly releasing a corpus makes that reuse possible; actual inclusion in a provider\'s training data depends on that provider\'s choices.'),
('They do not demonstrate transfer from the present social-science examples to empathy, clinical judgment, moral reliability, or cultural interpretation.', 'The next question is transfer: which scientific and social reasoning skills improve when the training material pairs formal structure with substantive interpretation?'),
('Raw Lean alone is unlikely to teach the full intended meaning.', 'Pairing Lean with an interpretation gives a learner both the deductive structure and its intended scientific meaning.'),
('a warning about the omitted mechanism', 'an explanation of which mechanism the model isolates and how that mechanism could be extended'),
('This is a real precedent for the broader idea; it does not demonstrate that the present repository contains such a system.', 'This establishes a route for extending the project into explicit normative theories.'),
('The goal would be auditable reasoning about values and consequences. A proof corpus cannot certify that an AI has acquired care, wisdom, or a complete grasp of social meaning.', 'The goal would be auditable reasoning about values and consequences: a model that can state an obligation, preserve its exceptions, identify a conflict, and explain how a conclusion changes when a premise changes. Those capabilities would be meaningful targets for an evaluation of ethical reasoning.'),
('More declarations would be valuable when they serve that purpose. The theorem count alone does not measure scientific progress.', 'Progress can be measured by the new research decisions the formalization makes possible.'),
('without pretending that a scheduling theorem is a complete theory of an institution', 'while connecting the scheduling result to the institution\'s observed constraints'),
('Here the target is a reduction in a specified reasoning error, not an undefined increase in “understanding.”', 'The target is a reduction in a specified reasoning error, giving the broader ambition of improved understanding an observable test.'),
('There are two unproductive extremes. At one end, an entire discipline is promised before its constructs are specified. At the other, a growing collection of elementary facts accumulates without a research use. A useful middle scale is a model family tied to a measurement, experiment, or institutional problem.', 'A model family tied to a measurement, experiment, or institutional problem provides a productive scale for this research. The family is broad enough to compare meaningful alternatives and precise enough to connect a proof to an actual decision.'),
('Those links suggest a research program, not a finished theory of society. Its organizing criterion should be whether an extension makes a previously ambiguous scientific decision more explicit and testable. A single theorem that changes an experiment may matter more than dozens that rename familiar deductions.', 'Those links organize a research program around a clear criterion: an extension should make a previously ambiguous scientific decision more explicit and testable. A theorem that changes an experiment is a particularly tangible form of progress.')
])

edit('05-reflections-and-appendices.md',[
('This checklist is descriptive and is not an AMSTAR-2 score.', 'The checklist is a descriptive self-assessment. AMSTAR 2 has a different purpose: appraisal of systematic reviews of healthcare interventions (Shea et al., 2017).'),
('PRISMA and Cochrane habits are useful here as process questions: Were searches explicit? Were inclusion rules applied consistently? Did extraction preserve the original claim? Were changes in scope recorded? For this document, the scope expanded from an explanatory response to two academic manuscripts and a full theorem atlas. That expansion is recorded in the production history. It did not introduce a claim that a systematic review had been conducted.', 'PRISMA 2020 supplies useful reporting questions about search procedures, selection, and synthesis (Page et al., 2021). For this targeted map, those questions support a recorded search log, explicit inclusion purposes, and per-source access information. A systematic extension would add a preregistered protocol and comprehensive database strategy.'),
('AMSTAR-2 evaluates systematic reviews in a different evidential setting, and RoB-2 evaluates randomized trials. Applying either as if these theorem declarations were clinical studies would misclassify the material. A future clinical evidence synthesis would use the appropriate instrument for the study design. The current audit instead evaluates traceability, extraction fidelity, semantic interpretation, and reproducibility.', 'Risk-of-bias tools should follow the object being appraised. RoB 2 addresses randomized trials (Sterne et al., 2019), while this source audit evaluates traceability, extraction fidelity, semantic interpretation, and reproducibility. A future evidence synthesis connecting a formal model to intervention studies would add the corresponding study-design appraisal.'),
('The files are import-ready resources. This task creates no live Zotero collection and makes no changes to a private Obsidian vault.', 'The files support independent import and reuse in a reference manager or Markdown knowledge base.')
])

edit('article-draft.md',[
('The unit of contribution is therefore a connected argument or reusable model property, not each declaration considered as an independent discovery.', 'The connected argument and reusable model property are the relevant units for assessing the library\'s scientific contribution.'),
('This is a transparent author-defined checklist, not an AMSTAR-2 score or a validated quality instrument.', 'This author-defined checklist is a descriptive self-assessment. AMSTAR 2 addresses the appraisal of systematic reviews of healthcare interventions (Shea et al., 2017).'),
('No claim of independent replication of those studies is made.', 'The source register preserves the distinction between a reported precedent and an independently reproduced result.')
])

# Public-facing brief: lead with the usable achievements and their evidence.
(P/'00-decision-brief.md').write_text('''# Executive Summary

**A well-chosen formal model can show which observation separates competing explanations, which measurement bias changes a conclusion, and which participant loses under an apparently beneficial arrangement. The project makes those insights inspectable through 67 checked Lean declarations.**

The integrated release links seven areas of scientific reasoning: solidarity (16 declarations), measurement (9), identifiability (9), causality (6), learning (9), collective action (10), and aggregation (8). Its contribution is the connected artifact: definitions, proofs, concrete counterexamples, explanations, and a commit-linked verification record. Supporting lemmas and combined results make the argument reusable.

The models are minimal mathematical representations of social systems and research procedures. They isolate a relationship so it can be understood exactly and extended deliberately. The strongest examples achieve substantial generality within their definitions: a bias interval holds for every admissible integer input; two probes identify every pair in the candidate space; an information-limit theorem applies to every estimator receiving the specified observational object.

| Finding | Evidence and next use |
|---|---|
| All 67 declarations are present and named in the dependency audit. | Direct inspection of the pinned source and successful CI record; a separately reproduced build would add verification independence. |
| Formal approaches span the named biological and social disciplines. | Primary examples establish methodological traditions and concrete precedents. |
| Proofs make research assumptions and consequences inspectable. | The worked examples show how the formal structure guides a measurement, design, or interpretation question. |
| Verified data and checker feedback can support AI theorem proving. | Primary training reports establish a technical precedent for the proposed paired corpus. |
| Transfer to scientific interpretation is an experimentally testable opportunity. | Compare representations and checker access on held-out model families, with formal and semantic evaluation. |

Five results offer especially clear entry points: the bounded measurement-bias interval; identification through a second probe; identical observations with different intervention effects; collective surplus with failed participation; and reversal of rates under pooling. Each makes a consequential distinction visible.

The immediate research program is to select one measurement or design problem, enrich its model, pair the proof with recovery analysis, obtain domain review, and test the resulting reasoning artifact in human or AI use. Context and retrieval provide an immediate route to using the material; parameter-updating training is a separate development route.

The source was inspected at commit `780f1b83aef15a9cf455566bab9df2a47d738074`. GitHub Actions run [36392008029](https://github.com/Sodelin/Formalizing-Soft-Sciences/actions/runs/36392008029) reports a successful Lean 4.19.0 build and audit for that commit. This edition adds interpretation and synthesis based on that recorded verification.
''')

data=json.loads(Path('references-data.json').read_text())
new=[
('R19','SheaEtAl2017','Shea, B. J. and Reeves, B. C. and Wells, G. and Thuku, M. and Hamel, C. and Moran, J. and Moher, D. and Tugwell, P. and Welch, V. and Kristjansson, E. and Henry, D. A.','2017','AMSTAR 2: A critical appraisal tool for systematic reviews that include randomised or non-randomised studies of healthcare interventions, or both','358','j4008','10.1136/bmj.j4008','Shea et al., 2017'),
('R20','PageEtAl2021','Page, M. J. and McKenzie, J. E. and Bossuyt, P. M. and Boutron, I. and Hoffmann, T. C. and Mulrow, C. D. and Shamseer, L. and Tetzlaff, J. M. and Akl, E. A. and Brennan, S. E. and Chou, R. and Glanville, J. and Grimshaw, J. M. and Hróbjartsson, A. and Lalu, M. M. and Li, T. and Loder, E. W. and Mayo-Wilson, E. and McDonald, S. and McGuinness, L. A. and Stewart, L. A. and Thomas, J. and Tricco, A. C. and Welch, V. A. and Whiting, P. and Moher, D.','2021','The PRISMA 2020 statement: An updated guideline for reporting systematic reviews','372','n71','10.1136/bmj.n71','Page et al., 2021'),
('R21','SterneEtAl2019','Sterne, J. A. C. and Savović, J. and Page, M. J. and Elbers, R. G. and Blencowe, N. S. and Boutron, I. and Cates, C. J. and Cheng, H.-Y. and Corbett, M. S. and Eldridge, S. M. and Emberson, J. R. and Hernán, M. A. and Hopewell, S. and Hróbjartsson, A. and Junqueira, D. R. and Jüni, P. and Kirkham, J. J. and Lasserson, T. and Li, T. and McAleenan, A. and Reeves, B. C. and Shepperd, S. and Shrier, I. and Stewart, L. A. and Tilling, K. and White, I. R. and Whiting, P. F. and Higgins, J. P. T.','2019','RoB 2: A revised tool for assessing risk of bias in randomised trials','366','l4898','10.1136/bmj.l4898','Sterne et al., 2019')]
for id,key,author,year,title,vol,pages,doi,cite in new:
    authors=author.split(' and ')
    auth=(', '.join(authors[:-1])+', & '+authors[-1]) if len(authors)<=20 else (', '.join(authors[:19])+', . . . '+authors[-1])
    data.append(dict(id=id,key=key,author=author,year=year,title=title,type='article',journal='BMJ',volume=vol,pages=pages,doi=doi,url='https://doi.org/'+doi,apa=f'{auth} ({year}). {title}. *BMJ, {vol}*, Article {pages}. https://doi.org/{doi}',cite=cite,access='Primary publisher abstract and bibliographic metadata, with PubMed author-list cross-check. Used for the stated purpose of the appraisal/reporting instrument.',tags='research-methods;critical-appraisal;access/abstract'))
Path('references-data.json').write_text(json.dumps(data,ensure_ascii=False,indent=2))
print('Revised public framing and recorded 21 sources.')
